version: "3.8"

services:
  all:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#  frontend:
#    build:
#      context: frontend
#      dockerfile: ../docker/frontend/Dockerfile
#    ports:
#      - "8080:80"
#    links:
#      - backend
#  backend:
#    build:
#      context: .
#      dockerfile: docker/backend/Dockerfile
#    ports:
#      - "8000:8000"
