version: "3.8"

services:
  frontend:
    build:
      context: frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "4200:80"
    links:
      - backend
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
