apiVersion: v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: agtern-deployment
  labels:
    app: agtern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agtern
  template:
    metadata:
      labels:
        app: agtern
    spec:
      containers:
      - name: agtern
        image: jeremyeastham/agtern:dev
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: log-volume
          mountPath: /app/log
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: agtern-service
spec:
  selector:
    app: agtern
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
