apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-storage
spec:
  interval: 1m
  url: https://charts.longhorn.io

---

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-storage
spec:
  interval: 5m
  targetNamespace: longhorn-system
  chart:
    spec:
      chart: longhorn
      version: "1.6.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 1m
  # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
  values:
    persistence:
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
    longhornUI:
      replicas: 1
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1
  install:
    createNamespace: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-block-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: dobs.csi.digitalocean.com