apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord-webhook
  namespace: flux-monitoring
spec:
  type: discord
  channel: deployment
  address: "https://discord.com/api/webhooks/1221565643434758274/SagIGpo450kL1kbYNomzngSB3hgnULg9SXZP-Wnx9783t_SVFJ5XJ-fzY3ESIC4QSOEQ"

---

apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord-alerts
  namespace: flux-monitoring
spec:
  providerRef:
    name: discord-webhook
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
      namespace: flux-system
    - kind: Kustomization
      name: "*"
      namespace: flux-system
    - kind: HelmChart
      name: "*"
      namespace: flux-system
    - kind: HelmRelease
      name: "*"
      namespace: flux-system