apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
resources:
  - namespaces.yaml
  - discord.yaml
  - metrics-server.yaml
#  - kubernetes-dashboard.yaml