apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/flux-monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agtern-dependencies
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./flux/agtern-dependencies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system