apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: agtern-dependencies
spec:
  interval: 1m
  url: https://bitnami-labs.github.io/sealed-secrets

---

apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: agtern-dependencies
spec:
  interval: 5m
  targetNamespace: secrets
  chart:
    spec:
      chart: sealed-secrets
      version: "2.15.2"
      sourceRef:
        kind: HelmRepository
        name: kubernetes-dashboard
      interval: 1m
  # https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml
  values: {}
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace